/** @file schema_sql.h
 *  @ingroup group_store
 *  @brief Embedded copy of schema/schema.sql (generated; do not edit by hand). */
#ifndef AIGATE_SCHEMA_SQL_H
#define AIGATE_SCHEMA_SQL_H

#define AIGATE_SCHEMA_VERSION 18

static const char SCHEMA_SQL[] =
    "-- aigate schema (version 1); applied by pg_store_migrate() in one transaction.\n"
    "-- Idempotent: safe to re-run; schema_migrations tracks applied versions.\n"
    "CREATE TABLE IF NOT EXISTS api_keys (\n"
    "  key_id          BIGSERIAL PRIMARY KEY,\n"
    "  key_hash        TEXT NOT NULL,\n"
    "  name            TEXT NOT NULL,\n"
    "  allowed_models  TEXT[] NOT NULL DEFAULT '{}',\n"
    "  rate_qps        INT NOT NULL DEFAULT 0,\n"
    "  daily_token_quota INT NOT NULL DEFAULT 0,\n"
    "  expires_at      TIMESTAMPTZ,\n"
    "  revoked_at      TIMESTAMPTZ,\n"
    "  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()\n"
    ");\n"
    "CREATE UNIQUE INDEX IF NOT EXISTS ux_api_keys_hash ON api_keys (key_hash);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS models (\n"
    "  model_name       TEXT PRIMARY KEY,\n"
    "  provider         TEXT NOT NULL,\n"
    "  endpoint         TEXT NOT NULL,\n"
    "  upstream_key_ref TEXT,\n"
    "  default_params   JSONB NOT NULL DEFAULT '{}',\n"
    "  enabled          BOOLEAN NOT NULL DEFAULT true\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS upstream_secrets (\n"
    "  ref      TEXT PRIMARY KEY,\n"
    "  cipher   BYTEA NOT NULL,\n"
    "  provider TEXT NOT NULL\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS usage_daily (\n"
    "  key_id          BIGINT NOT NULL REFERENCES api_keys(key_id) ON DELETE CASCADE,\n"
    "  model_name      TEXT NOT NULL REFERENCES models(model_name) ON DELETE CASCADE,\n"
    "  day             DATE NOT NULL,\n"
    "  requests        BIGINT NOT NULL DEFAULT 0,\n"
    "  prompt_tokens   BIGINT NOT NULL DEFAULT 0,\n"
    "  completion_tokens BIGINT NOT NULL DEFAULT 0,\n"
    "  errors          BIGINT NOT NULL DEFAULT 0,\n"
    "  PRIMARY KEY (key_id, model_name, day)\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS admin_tokens (\n"
    "  token_hash TEXT PRIMARY KEY,\n"
    "  name       TEXT NOT NULL,\n"
    "  created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n"
    ");\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS schema_migrations (\n"
    "  version    INT PRIMARY KEY,\n"
    "  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()\n"
    ");\n"
    "\n"
    "INSERT INTO schema_migrations(version) VALUES (1) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v2: prompt cache token metering\n"
    "ALTER TABLE usage_daily ADD COLUMN IF NOT EXISTS cached_prompt_tokens BIGINT NOT NULL DEFAULT 0;\n"
    "INSERT INTO schema_migrations(version) VALUES (2) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v3: multi-upstream targets & load balancing policy\n"
    "ALTER TABLE models ADD COLUMN IF NOT EXISTS targets JSONB NOT NULL DEFAULT '[]';\n"
    "ALTER TABLE models ADD COLUMN IF NOT EXISTS lb_policy TEXT NOT NULL DEFAULT 'priority';\n"
    "INSERT INTO schema_migrations(version) VALUES (3) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v4: upstream providers management\n"
    "CREATE TABLE IF NOT EXISTS providers (\n"
    "  id            BIGSERIAL PRIMARY KEY,\n"
    "  name          TEXT NOT NULL UNIQUE,\n"
    "  provider_type TEXT NOT NULL,\n"
    "  endpoint      TEXT NOT NULL,\n"
    "  api_key       TEXT NOT NULL DEFAULT '',\n"
    "  models        TEXT[] NOT NULL DEFAULT '{}',\n"
    "  enabled       BOOLEAN NOT NULL DEFAULT true,\n"
    "  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),\n"
    "  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()\n"
    ");\n"
    "INSERT INTO schema_migrations(version) VALUES (4) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v5: BIGINT quota + model name length guard (matches C 128 cap)\n"
    "ALTER TABLE api_keys ALTER COLUMN daily_token_quota TYPE BIGINT;\n"
    "DO $$\n"
    "BEGIN\n"
    "    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_models_name_len') THEN\n"
    "        ALTER TABLE models ADD CONSTRAINT ck_models_name_len CHECK (char_length(model_name) <= 127);\n"
    "    END IF;\n"
    "END\n"
    "$$;\n"
    "INSERT INTO schema_migrations(version) VALUES (5) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v6: per-request usage audit detail (P0-1)\n"
    "CREATE TABLE IF NOT EXISTS usage_requests (\n"
    "  key_id          BIGINT NOT NULL,\n"
    "  model_name      TEXT NOT NULL,\n"
    "  provider        TEXT NOT NULL DEFAULT '',\n"
    "  http_status     INT NOT NULL,\n"
    "  prompt_tokens   BIGINT NOT NULL DEFAULT 0,\n"
    "  completion_tokens BIGINT NOT NULL DEFAULT 0,\n"
    "  cached_prompt_tokens BIGINT NOT NULL DEFAULT 0,\n"
    "  latency_ns      BIGINT NOT NULL DEFAULT 0,\n"
    "  ts              BIGINT NOT NULL\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_usage_requests_key_ts ON usage_requests (key_id, ts);\n"
    "CREATE INDEX IF NOT EXISTS ix_usage_requests_ts ON usage_requests (ts);\n"
    "INSERT INTO schema_migrations(version) VALUES (6) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v7: dept groups + model pricing (internal SaaS cost attribution)\n"
    "CREATE TABLE IF NOT EXISTS groups (\n"
    "  id         BIGSERIAL PRIMARY KEY,\n"
    "  name       TEXT NOT NULL UNIQUE,\n"
    "  created_at TIMESTAMPTZ NOT NULL DEFAULT now()\n"
    ");\n"
    "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS group_id BIGINT\n"
    "  REFERENCES groups(id) ON DELETE SET NULL;\n"
    "ALTER TABLE models ADD COLUMN IF NOT EXISTS pricing JSONB NOT NULL DEFAULT '{}';\n"
    "INSERT INTO schema_migrations(version) VALUES (7) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v8: reasoning tokens for OpenAI Responses API / CoT models\n"
    "ALTER TABLE usage_requests ADD COLUMN IF NOT EXISTS reasoning_tokens BIGINT NOT NULL DEFAULT 0;\n"
    "INSERT INTO schema_migrations(version) VALUES (8) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v9: guardrails rules and budget limits\n"
    "CREATE TABLE IF NOT EXISTS guardrails_rules (\n"
    "  id          BIGSERIAL PRIMARY KEY,\n"
    "  rule_type   TEXT NOT NULL,\n"
    "  pattern     TEXT NOT NULL,\n"
    "  action      TEXT NOT NULL DEFAULT 'block',\n"
    "  category    TEXT NOT NULL DEFAULT 'general',\n"
    "  enabled     BOOLEAN NOT NULL DEFAULT true,\n"
    "  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_guardrails_enabled ON guardrails_rules(enabled, rule_type);\n"
    "\n"
    "ALTER TABLE api_keys \n"
    "  ADD COLUMN IF NOT EXISTS guardrails_enabled BOOLEAN NOT NULL DEFAULT true,\n"
    "  ADD COLUMN IF NOT EXISTS monthly_cost_budget NUMERIC(12, 4) NOT NULL DEFAULT 0.0000,\n"
    "  ADD COLUMN IF NOT EXISTS monthly_token_budget BIGINT NOT NULL DEFAULT 0;\n"
    "\n"
    "ALTER TABLE groups \n"
    "  ADD COLUMN IF NOT EXISTS monthly_budget_usd NUMERIC(12, 4) NOT NULL DEFAULT 0.0000;\n"
    "\n"
    "ALTER TABLE usage_requests \n"
    "  ADD COLUMN IF NOT EXISTS guardrail_action TEXT NOT NULL DEFAULT '';\n"
    "\n"
    "INSERT INTO schema_migrations(version) VALUES (9) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v10: prompt templates and modes for models and api_keys\n"
    "ALTER TABLE models\n"
    "  ADD COLUMN IF NOT EXISTS system_prompt TEXT DEFAULT NULL,\n"
    "  ADD COLUMN IF NOT EXISTS prompt_mode INT NOT NULL DEFAULT 0;\n"
    "\n"
    "ALTER TABLE api_keys\n"
    "  ADD COLUMN IF NOT EXISTS system_prompt TEXT DEFAULT NULL,\n"
    "  ADD COLUMN IF NOT EXISTS prompt_mode INT NOT NULL DEFAULT 0;\n"
    "\n"
    "INSERT INTO schema_migrations(version) VALUES (10) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v11: external webhook moderation plugin support\n"
    "ALTER TABLE guardrails_rules\n"
    "  ADD COLUMN IF NOT EXISTS webhook_secret TEXT DEFAULT NULL,\n"
    "  ADD COLUMN IF NOT EXISTS timeout_ms INT NOT NULL DEFAULT 500,\n"
    "  ADD COLUMN IF NOT EXISTS fail_mode VARCHAR(16) NOT NULL DEFAULT 'open',\n"
    "  ADD COLUMN IF NOT EXISTS phase VARCHAR(16) NOT NULL DEFAULT 'inbound';\n"
    "\n"
    "INSERT INTO schema_migrations(version) VALUES (11) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v12: adaptive latency routing & hedged requests support\n"
    "ALTER TABLE models\n"
    "  ADD COLUMN IF NOT EXISTS hedged_delay_ms INT NOT NULL DEFAULT 0,\n"
    "  ADD COLUMN IF NOT EXISTS hedge_budget_pct INT NOT NULL DEFAULT 15,\n"
    "  ADD COLUMN IF NOT EXISTS hedged_enabled BOOLEAN NOT NULL DEFAULT FALSE;\n"
    "\n"
    "INSERT INTO schema_migrations(version) VALUES (12) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v13: traffic shadowing and canary A/B testing rules\n"
    "CREATE TABLE IF NOT EXISTS shadow_rules (\n"
    "  id              BIGSERIAL PRIMARY KEY,\n"
    "  source_model    TEXT NOT NULL,\n"
    "  target_model    TEXT NOT NULL,\n"
    "  target_provider TEXT NOT NULL DEFAULT '',\n"
    "  mode            VARCHAR(16) NOT NULL DEFAULT 'shadow',\n"
    "  sample_rate     DOUBLE PRECISION NOT NULL DEFAULT 1.0,\n"
    "  header_match    TEXT NOT NULL DEFAULT '',\n"
    "  enabled         BOOLEAN NOT NULL DEFAULT true,\n"
    "  timeout_ms      INT NOT NULL DEFAULT 10000,\n"
    "  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS ix_shadow_rules_enabled ON shadow_rules(enabled, source_model);\n"
    "INSERT INTO schema_migrations(version) VALUES (13) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v14: prompt compression and token pruning rules\n"
    "CREATE TABLE IF NOT EXISTS compressor_rules (\n"
    "    id                  VARCHAR(36) PRIMARY KEY,\n"
    "    model_pattern       VARCHAR(64) NOT NULL,\n"
    "    enabled             BOOLEAN NOT NULL DEFAULT TRUE,\n"
    "    level               INTEGER NOT NULL DEFAULT 1,\n"
    "    min_tokens          INTEGER NOT NULL DEFAULT 2048,\n"
    "    max_history_turns   INTEGER NOT NULL DEFAULT 6,\n"
    "    target_ratio        DOUBLE PRECISION NOT NULL DEFAULT 0.60,\n"
    "    preserve_system     BOOLEAN NOT NULL DEFAULT TRUE,\n"
    "    preserve_code       BOOLEAN NOT NULL DEFAULT TRUE,\n"
    "    preserve_tools      BOOLEAN NOT NULL DEFAULT TRUE,\n"
    "    created_at          BIGINT NOT NULL,\n"
    "    updated_at          BIGINT NOT NULL\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_compressor_rules_model ON compressor_rules(enabled, model_pattern);\n"
    "INSERT INTO schema_migrations(version) VALUES (14) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v15: prompt cache prefix alignment and optimization rules\n"
    "CREATE TABLE IF NOT EXISTS cache_optimizer_rules (\n"
    "    id                          VARCHAR(36) PRIMARY KEY,\n"
    "    model_pattern               VARCHAR(64) NOT NULL,\n"
    "    enabled                     BOOLEAN NOT NULL DEFAULT TRUE,\n"
    "    sort_tools                  BOOLEAN NOT NULL DEFAULT TRUE,\n"
    "    sink_dynamic_system         BOOLEAN NOT NULL DEFAULT TRUE,\n"
    "    inject_anthropic_breakpoints BOOLEAN NOT NULL DEFAULT TRUE,\n"
    "    min_tokens_threshold        INTEGER NOT NULL DEFAULT 1024,\n"
    "    created_at                  BIGINT NOT NULL,\n"
    "    updated_at                  BIGINT NOT NULL\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_cache_optimizer_rules_model ON cache_optimizer_rules(enabled, model_pattern);\n"
    "INSERT INTO schema_migrations(version) VALUES (15) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v16: persistent audit violations for compliance and forensics\n"
    "CREATE TABLE IF NOT EXISTS audit_violations (\n"
    "    id                  BIGSERIAL PRIMARY KEY,\n"
    "    trace_id            VARCHAR(64) NOT NULL,\n"
    "    tenant_id           VARCHAR(64) NOT NULL DEFAULT '',\n"
    "    client_ip           VARCHAR(48) NOT NULL DEFAULT '',\n"
    "    model               VARCHAR(64) NOT NULL,\n"
    "    routed_model        VARCHAR(64) NOT NULL DEFAULT '',\n"
    "    severity            VARCHAR(16) NOT NULL,\n"
    "    rule_tag            VARCHAR(64) NOT NULL,\n"
    "    http_status         INT NOT NULL DEFAULT 400,\n"
    "    ttft_ms             INT NOT NULL DEFAULT 0,\n"
    "    total_latency_ms    INT NOT NULL DEFAULT 0,\n"
    "    fallback_reason     VARCHAR(32) NOT NULL DEFAULT '',\n"
    "    prompt_snapshot     TEXT,\n"
    "    completion_snapshot TEXT,\n"
    "    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_audit_violations_search ON audit_violations (tenant_id, model, rule_tag, created_at DESC);\n"
    "CREATE INDEX IF NOT EXISTS idx_audit_violations_trace ON audit_violations (trace_id);\n"
    "INSERT INTO schema_migrations(version) VALUES (16) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v17: zero-width watermark enabling on api_keys\n"
    "ALTER TABLE api_keys\n"
    "  ADD COLUMN IF NOT EXISTS watermark_enabled BOOLEAN NOT NULL DEFAULT false;\n"
    "\n"
    "INSERT INTO schema_migrations(version) VALUES (17) ON CONFLICT (version) DO NOTHING;\n"
    "\n"
    "-- Migration v18: Canary honey-tokens and dynamic threat defense whitelists\n"
    "ALTER TABLE api_keys\n"
    "  ADD COLUMN IF NOT EXISTS is_canary BOOLEAN NOT NULL DEFAULT false;\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS threat_rule_whitelists (\n"
    "  rule_id         BIGSERIAL PRIMARY KEY,\n"
    "  name            VARCHAR(64) NOT NULL,\n"
    "  match_key_id    BIGINT NOT NULL DEFAULT 0,\n"
    "  match_model     VARCHAR(64) NOT NULL DEFAULT '',\n"
    "  bypass_rule_tag VARCHAR(64) NOT NULL DEFAULT '*',\n"
    "  reason          TEXT NOT NULL DEFAULT '',\n"
    "  enabled         BOOLEAN NOT NULL DEFAULT true,\n"
    "  expires_at      TIMESTAMPTZ,\n"
    "  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()\n"
    ");\n"
    "CREATE INDEX IF NOT EXISTS idx_threat_whitelists_lookup \n"
    "  ON threat_rule_whitelists (match_key_id, match_model, enabled);\n"
    "\n"
    "CREATE TABLE IF NOT EXISTS ip_bans_persistent (\n"
    "  ip              VARCHAR(48) PRIMARY KEY,\n"
    "  reason          VARCHAR(64) NOT NULL,\n"
    "  expires_at      TIMESTAMPTZ NOT NULL,\n"
    "  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()\n"
    ");\n"
    "\n"
    "INSERT INTO schema_migrations(version) VALUES (18) ON CONFLICT (version) DO NOTHING;\n";

#endif /* AIGATE_SCHEMA_SQL_H */
