file(GLOB UNIT_TEST_SRC ${CMAKE_SOURCE_DIR}/tests/unit/*.c)
add_executable(aigate_unit_tests ${UNIT_TEST_SRC})
target_link_libraries(aigate_unit_tests PRIVATE libaigate civetweb-c-library OpenSSL::Crypto)
add_dependencies(aigate_unit_tests civetweb-c-library)
add_test(NAME unit COMMAND aigate_unit_tests)
